#!/bin/bash
mkdir -m 751 my_dir
[master dd5ac80] update script that creates a directory called my_dir with permissions 751 in the working directory
 2 files changed, 2 insertions(+), 2 deletions(-)
 create mode 100755 0x01-shell_permissions/12-directory_permissions
 delete mode 100755 0x01-shell_permissions/9-John_Doe
